; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[Spotify]
text               = cdd6f4
subtext            = a6adc8
main               = 000000
header             = b4befe
highlight          = 1a1a1a
accent             = b4befe
accent-active      = b4befe
accent-inactive    = 6c7086
border-active      = b4befe
border-inactive    = 313244
banner             = b4befe
notification       = b4befe
notification-error = f38ba8